### ISSUE TITLE
Readme (Flashing tutorial) outdated?

### ISSUE THREAD

**Issue by codebude** [dudanov/iot-uni-dongle#25]
Hello,

I am in the process of rebuilding your stick and am trying to follow the Readme.md/Flashing.md. I find the instructions in the [flashing tutorial](https://github.com/dudanov/iot-uni-dongle/blob/main/FLASHING.md) confusing. Is the code still up to date?

```yaml
substitutions:
  name: my-esphome-device
  friendly_name: My ESPHome Device

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Must be used once. It is necessary to comment out after the first firmware update.
  use_address: iot-uni-dongle.local

packages:
  default: github://dudanov/esphome-packages/hardware/iot-uni-dongle/device.yaml
```

Furthermore there is an AC demo file linked in the tutorial: 

> [Here](https://github.com/dudanov/iot-uni-dongle/blob/main/electrolux-ac-esp8266.yaml) you can view example YAML config for Midea-like ACs.

In the meantime, the package seems to have officially made it to ESPHome. Wouldn't it be more elegant to refer directly to the ESPHome package in the flashing instructions?
